stages:
  build_job_function_embedding_cache:
    cmd: >-
      poetry run python src/embeddings/build_job_function.py
      --job-function-cache-output ${embedding_paths.job_function_cache}
    deps:
      - data/datasets/postings_final.csv
      - src/embeddings/build_job_function.py
      - src/embeddings/job_function.py
      - src/embeddings/utils.py
    params:
      - models.encoder_model_name
      - embedding_paths.job_function_cache
    outs:
      - ${embedding_paths.job_function_cache}

  build_skill_embedding_cache:
    cmd:  >-
      poetry run python src/embeddings/build_skill.py
      --skill-cache-output ${embedding_paths.skill_cache}
    deps:
      - data/datasets/postings_final.csv
      - src/embeddings/build_skill.py
      - src/embeddings/skills.py
      - src/embeddings/utils.py
    params:
      - models.encoder_model_name
      - embedding_paths.skill_cache
    outs:
      - ${embedding_paths.skill_cache}
